### ISSUE TITLE
SQLAlchemy support is not completed

### ISSUE THREAD

**Issue by urugang** [taosdata/taos-connector-python#117]
## all connecting way has such errors.
```
engine= sqlalchemy.create_engine('taosws://root:taosdata@localhost:6041')
df.read_sql('show stables',engine)
```
``` 
AttributeError: 'AlchemyTaosConnection' object has no attribute 'Error'
```
## can not change database, or connect with database directly

 ```
engine= sqlalchemy.create_engine('taosws://root:taosdata@localhost:6041/log')
```

**Comment by sangshuduo** [comment]
> ## all connecting way has such errors.
> 
> ```
> engine= sqlalchemy.create_engine('taosws://root:taosdata@localhost:6041')
> df.read_sql('show stables',engine)
> ```
> 
> ```
> AttributeError: 'AlchemyTaosConnection' object has no attribute 'Error'
> ```
> 
> ## can not change database, or connect with database directly
> 
> ```
> engine= sqlalchemy.create_engine('taosws://root:taosdata@localhost:6041/log')
> ```

Thanks for your issue. We will fix it soon. Please use taosrest to create engine first.

**Comment by urugang** [comment]
> > ## all connecting way has such errors.
both return 'database not specified' with taosrest.
```
engine = sqlalchemy.create_engine("taosrest://root:taosdata@localhost:6041")
engine.execute("use information_schema")
pd.read_sql("show stables", engine)

engine = sqlalchemy.create_engine(
    "taosrest://root:taosdata@localhost:6041/information_schema"
)
pd.read_sql("show stables", engine)

```
```
    raise ConnectError(resp["desc"], resp["code"])
sqlalchemy.exc.DBAPIError: (taosrest.errors.ConnectError) [0x2600]: database not specified
[SQL: show stables]
(Background on this error at: https://sqlalche.me/e/14/dbapi)
```

**Comment by sangshuduo** [comment]
pip3 install -U taospy

![image](https://user-images.githubusercontent.com/825729/208589382-8b2174a3-8980-4cbd-b05c-3a5192877f11.png)

**Comment by urugang** [comment]
thanks
