### ISSUE TITLE
TaosResult.row_count  seems to always be 0.

### ISSUE THREAD

**Issue by nowgoo** [taosdata/taos-connector-python#18]
不管结果集中是否有数据，TaosResult.row_count 一直是 0。TaosResult.field_count 正常。
版本 2.2.1

**Comment by nowgoo** [comment]
taos/result.py shows TaosResult.row_count was assigned in TaosResult.fetch_all(), it would be good if row_count is available before calling fetch_all().

**Comment by fenghua1997** [comment]
Thanks for the feedback. We'll take a look.

**Comment by dingbo8128** [comment]
> taos/result.py shows TaosResult.row_count was assigned in TaosResult.fetch_all(), it would be good if row_count is available before calling fetch_all().

It's  not possible for now due to the design of  the client library.
