### ISSUE TITLE
流函数支持

### ISSUE THREAD

**Issue by OdinLin** [taosdata/taos-connector-python#183]
你好，注意到tdengine的python库没有支持例如创建流和定义流逻辑等，翻看历史之前好像有这个示例但已经被删除并且写法也不是很pythonic，请问后续是否有对这块的支持，或者是基于其他的考量不支持， 谢谢

**Comment by sangshuduo** [comment]
3.0 重新设计了流计算，Python接口参见： https://docs.taosdata.com/connector/python/#%E6%95%B0%E6%8D%AE%E8%AE%A2%E9%98%85
