### ISSUE TITLE
python库query结果非utc时间，造成数据有8小时误差

### ISSUE THREAD

**Issue by lonelyleaf** [taosdata/taos-connector-python#21]
使用的unix时间戳插入数据，然后用python库查询时，时间差了8个小时，且datetime对象没有时区信息。

使用python代码查询

```python
import taos

conn = taos.connect(host="127.0.0.1", user="root", password="taosdata")
conn.select_db("db")

r = conn.query("select time,value from  local_pac_test.test_ts_table2 limit 10")



for v in r:
    print(v)
    print(f"time:{v[0]}  value:{v[1]}")
```

结果
```
(datetime.datetime(2022, 3, 24, 16, 50, 18, 393000), 1.0)
time:2022-03-24 16:50:18.393000  value:1.0
```

使用taos命令行查询

![image](https://user-images.githubusercontent.com/9879800/159890307-47791079-8e3f-4c9d-84e4-a3d771e6d0a3.png)

python时间库处理时区问题是有点蠢……应该是直接使用datetime初始化时间，又没有添加时区信息导致的

有没有办法设定返回datetime对象的默认时区，或者直接返回时间戳的float或int？

**Comment by zitsen** [comment]
Connector 使用本地时区，如果需要使用UTC时间，可以显示地在 /etc/taos/taos.cfg 中设置 `timezone UTC`

**Comment by sangshuduo** [comment]
新版本支持了在连接时指定 timezone

**Comment by sangshuduo** [comment]
close issue since no response for a long time.
