### ISSUE TITLE
taos-ws-py 查询结果循环输出报错

### ISSUE THREAD

**Issue by ZH-Sun-lab** [taosdata/taos-connector-python#219]
TD版本：
3.1.0.0

连接器版本：
taos-ws-py : 0.2.5

![641338758bcc7ccd7008df206b98222](https://github.com/taosdata/taos-connector-python/assets/8124117/ab679995-1c02-46f8-aa18-89623724ca60)

报错代码：
host = 'XXXXXX'
port = 6041
user = 'XXXXX'
password = 'XXXXXX'
database = 'XXXXX'

self.conn: taosws.Connection = taosws.connect(f"taosws://{user}:{password}@{host}:{port}/{database}")

query = f"select _wstart, max(out_power), dev_id from td_manabox.super_pv_pcs_data where dev_id in ('2016010235100099') and ts >= '2023-08-29T17:02:20+08:00' and ts <= '2023-09-05T17:02:20+08:00' partition by dev_id interval(5m);"
result: taosws.TaosResult = self.conn.query(query)
cnt = 1
for res in result:
    print(cnt, res)

报错内容：

![image](https://github.com/taosdata/taos-connector-python/assets/8124117/36b26225-8eb1-4859-aa1b-c84b51a6dec6)

**Comment by sunpe** [comment]
使用 0.2.5 版本的 taos-ws-py，使用 taosBenchmark 产生的数据做测试，测试代码为
```
def test_query():
    conn = taosws.connect('taosws://root:taosdata@localhost:6041')
    res = conn.query('select _wstart, max(voltage), groupid from test.meters partition by location interval(10s)')
    for r in res:
        print(r)
```
测试没问题。我暂时修改了报错位置的代码，暂时屏蔽掉了错误。

还请提供完整的能复现问题的代码，以便我们能发现真正的问题。

**Comment by ZH-Sun-lab** [comment]
完整代码&报错如下：
![image](https://github.com/taosdata/taos-connector-python/assets/8124117/5239efff-42ba-416a-8642-6aae70d9d409)

如需更详细的复现，请联系我来公司实地演示。

**Comment by sunpe** [comment]
taos-ws-py 刚发布了 0.2.8，升级一下试试，应该可以解决这个问题

**Comment by ZH-Sun-lab** [comment]
新的结果如下：
![image](https://github.com/taosdata/taos-connector-python/assets/8124117/019f8524-911c-4527-bac8-e1e404518348)

描述：没有打印出全部目标查询结果，就输出终止了
猜测：taos-ws-py包对查询结果的最大数量处理有问题，目前来看是超过1024条就会出现该问题，麻烦确认排查一下。

**Comment by sunpe** [comment]
如果结果少于1024条会有问题吗

**Comment by sunpe** [comment]
问题已修复，升级到  0.2.9 版本
