### ISSUE TITLE
schemaless inserts are truncating time to even seconds

### ISSUE THREAD

**Issue by RonMatsu** [taosdata/taos-connector-python#280]
I'm trying to use the python library (taosws) to do schemaless inserts into TDengine 3.3.4.3 and it seems to be incapable of inserting timestamps with more precision than one second. I've tried all the available PySchemalessPrecision arguments (Microsecond, Nanosecond, etc.). 

expected behavior:

lines = [
{'metric': 'actualhighsidecurrentdc1',
  'timestamp': 1730229625.844247,
  'value': 2.3500000000001364,
  'tags': {'dataType': 'ufloat', 'units': 'A'}}
]
ar = conn.schemaless_insert([json.dumps(lines_all)], PySchemalessProtocol.Json, PySchemalessPrecision.Microsecond, 0, 0)

cur = conn.cursor()
cur.execute('select * from actualhighsidecurrentdc1')
res = cur.fetchall()

res[0][0].timestamp() 
Out: 1730229625.844247

observed behavior:
res[0][0].timestamp()
Out: 1730229625.0

**Comment by yu285** [comment]
It is okay , thanks for your support
