### ISSUE TITLE
Taospy=2.3.6 连接器关闭报 NoneType error

### ISSUE THREAD

**Issue by modaye** [taosdata/taos-connector-python#75]
``` Exception ignored in: <function TaosConnection.__del__ at 0x7fe4a38e5f70>
Traceback (most recent call last):
python3.9/site-packages/taos/connection.py", line 198, in __del__
python3.9/site-packages/taos/connection.py", line 59, in close
TypeError: 'NoneType' object is not callable
```
出错代码在 connection.py 第 59 行 taos_close(self._conn)

**Comment by sangshuduo** [comment]
@modaye 请提供可以重现的简单代码，谢谢

**Comment by zitsen** [comment]
我在多个版本下下均未复现。只能建议检查下环境。

**Comment by dingbo8128** [comment]
我在 windows 上 用多个版本 python 测试，也均无复现。 最好提供项目结构的细节。

**Comment by modaye** [comment]
确实是特定的项目才会复现该问题， 我在hellozai/ 目录下还有一个`models` 包, 包中的`model.py` 文件中 也导入了`taos` 用于其中函数的类型注解，经过测试只要在该 `model.py` 模块中导入 `taos` 就引发错误。

**Comment by modaye** [comment]
这是一个奇怪的问题，将代码copy 到其他由Pycharm 创建的项目下，并不会引发报错。

**Comment by modaye** [comment]
> 我在多个版本下下均未复现。只能建议检查下环境。

感谢

**Comment by modaye** [comment]
> 我在 windows 上 用多个版本 python 测试，也均无复现。 最好提供项目结构的细节。

感谢
