### ISSUE TITLE
pd.read_sql get timestamp when the db time precision is ns

### ISSUE THREAD

**Issue by wsf1990** [taosdata/taos-connector-python#93]
- taos version: 3.0.0.0
- taospy version: 2.6.2
DB's time precision is ns which create db by:create database xx precision 'ns'. And use pd.read_sql to read data from this db's table.But the time column is int64 type not datetime type.

**Comment by sangshuduo** [comment]
请参考：https://docs.taosdata.com/connector/python/#%E5%85%B3%E4%BA%8E%E7%BA%B3%E7%A7%92-nanosecond

**Comment by wsf1990** [comment]
谢谢！
