### ISSUE TITLE
AttributeError: /lib/libtaos.so: undefined symbol: taos_subscribe

### ISSUE THREAD

**Issue by qq876633655** [taosdata/taos-connector-python#98]
使用的3.0 TDengine
conn = taos.connect()
sub = conn.subscribe(True, "task_data", "select * from task;", 1000)

报错AttributeError: /lib/libtaos.so: undefined symbol: taos_subscribe
看了一下，cinterface.py第346行_libtaos.taos_subscribe(从库中找不到taos_subscribe方法

**Comment by sangshuduo** [comment]
pip3 install -U taospy
需要 Python3.7 以上版本

**Comment by qq876633655** [comment]
> 

我当前使用的py3.9，而且只有这个conn.subscribe方法不能用
暂时使用了循环查询数据库的方法代替，但是还是想使用订阅的方式

**Comment by sangshuduo** [comment]
这个函数取消了，换3.0 用新的数据订阅吧

**Comment by qq876633655** [comment]
是tmp那个吗？

**Comment by sangshuduo** [comment]
> 有尝试使用tmq的方式，但是未能实现，如果示例程序可以跑的话，会再次尝试看看

https://github.com/taosdata/taos-connector-python/blob/main/examples/tmq.py
